### ISSUE TITLE
[enhancement]增加readme

### ISSUE THREAD

**Issue by colommar** [EricHongXDD/smu_course_election_helper#4]
![image](https://github.com/EricHongXDD/smu_course_election_helper/assets/117348480/46dd957b-1f34-4311-92f1-f365016ce8c1)
似乎没能理解这个登录的逻辑？该如何获取验证码

**Comment by EricHongXDD** [comment]
右边的按钮，刷新验证码或重新登陆，点一下

**Comment by EricHongXDD** [comment]
你好，发现问题是软件似乎装在了C盘下的Program Files文件夹，导致软件没有权限写入获取到的验证码图片文件“captcha.png”，你尝试可以右键->以管理员身份运行；或者重新安装最新版本（最新版本会自动在运行时索求管理员权限）。此外，readme以上传，你可以查看，谢谢！
